version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: cityzen-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cityzen
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  cityzen-backend:
    build: .
    container_name: cityzen-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cityzen
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    command: ["./mvnw", "spring-boot:run"]

volumes:
  mysql_data:
